version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/*
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    networks:
      - mynetwork

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "955:80"
    depends_on:
      - frontend
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge